# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/VivadoProject/led_lights/led_lights.cache/wt [current_project]
set_property parent.project_path D:/VivadoProject/led_lights/led_lights.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/VivadoProject/led_lights/xilinx.com_user_ctc8_1.0 [current_project]
add_files -quiet D:/VivadoProject/led_lights/led_lights.runs/ctc8_0_synth_1/ctc8_0.dcp
set_property used_in_implementation false [get_files D:/VivadoProject/led_lights/led_lights.runs/ctc8_0_synth_1/ctc8_0.dcp]
read_verilog -library xil_defaultlib {
  D:/VivadoProject/led_lights/led_lights.srcs/sources_1/new/s_38.v
  D:/VivadoProject/led_lights/led_lights.srcs/sources_1/new/clock_div.v
  D:/VivadoProject/led_lights/led_lights.srcs/sources_1/new/led_lights.v
}
read_xdc D:/VivadoProject/led_lights/led_lights.srcs/constrs_1/new/constrs_1.xdc
set_property used_in_implementation false [get_files D:/VivadoProject/led_lights/led_lights.srcs/constrs_1/new/constrs_1.xdc]

synth_design -top led_lights -part xc7a100tcsg324-1
write_checkpoint -noxdef led_lights.dcp
catch { report_utilization -file led_lights_utilization_synth.rpt -pb led_lights_utilization_synth.pb }
